"""
Test suite for Step 1: Dataset Audit
Verifies that the audit summary exists, has valid structure, and contains expected keys and data types.
"""

import os
import json
import pytest

def test_sample_file_exists():
    assert os.path.exists("sample.csv"), "sample.csv should exist in the root directory"

def test_full_dataset_exists():
    assert os.path.exists("twcs.csv"), "twcs.csv should exist in the root directory"

def test_audit_summary_generated():
    audit_file = "data/audit/audit_summary.json"
    assert os.path.exists(audit_file), f"{audit_file} should have been generated by audit_dataset.py"
    
    with open(audit_file, "r") as f:
        data = json.load(f)
        
    expected_keys = [
        "file_size_mb", "total_rows", "columns", "null_counts",
        "inbound_counts", "root_tweets", "reply_tweets",
        "tweets_with_responses", "top_20_brands", "uber_brands"
    ]
    for key in expected_keys:
        assert key in data, f"Key '{key}' missing from audit summary"
        
    assert data["total_rows"] > 2_800_000, f"Expected >2.8M rows, got {data['total_rows']}"
    assert "Uber_Support" in data["top_20_brands"], "Uber_Support should be in top 20 brands"
    assert data["uber_brands"].get("Uber_Support", 0) > 50_000, "Expected >50,000 Uber_Support tweets"
